#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Spring Default Setup
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# name : project name
# rabbitmq : rabbitMq Setup
# jps : jpa setup
#
spring:
  application:
    name: customer-service
  rabbitmq:
    host: ${RABBITMQ_SERVER_URL:localhost}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: username
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  #H2 DB
  #  datasource:
  #    sql-script-encoding: UTF-8
  #    driverClassName: org.h2.Driver
  #    url: jdbc:h2:mem:customer;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
  #    username: ${DB_USERNAME:sa}
  #    password: ${DB_PASSWORD:}

  datasource:
    sql-script-encoding: UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:customer}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    encoding: UTF-8
#    baseline-version: 1
#    baseline-on-migrate: true

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Endpoint output options for Hystrix Stream
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/customers/api-docs

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# GraphQL
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schemaLocationPattern: "**/*.graphqls"
    introspectionEnabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
